### ISSUE TITLE
Base size modal should give a success message

### ISSUE THREAD

**Issue by aseea** [no222bd/1dv411-Webbprojekt-1#116]
Basesize modal need to indicate success with changing the base size. User needs to get to the cube in a logical way. (Jorryt's kommentarer 2015-02-18)

**Comment by aseea** [comment]
My suggestion is that u create two buttons in the main menu, that has the look of the buttons Jorryt suggests. That way the user stays with the cube at all time and you don't have to figure out a clever way of closing the modal without being an annoyance to the user.

**Comment by ch222kv** [comment]
Area you sure that is the best idea? The change of base size is at the moment a destructive action that removes all cubes. If you have those buttons on the main menu then the risk of clicking on them and destroying everything you got is a lot larger. 
And it would also be odd since the parts about the application that isn't vital, such as the color change, the views and the base size changing buttons are placed in modals so that they do not distract from the overall building.

**Comment by aseea** [comment]
Change of base size isn't done yet and we don't know yet if changing base size should remove all cubes or bring them onto the new base.

**Comment by ch222kv** [comment]
Well, no, but as it is right now, and since we haven't decided yet, it is destructive.
Changing base size isn't an integral part of the application, so filling the UI with more buttons isn't necessarily better.

**Comment by aseea** [comment]
New suggestion based on what Jorryt said about clearing of cubes. Maybe top view perspective should show to the left, where clearing cubes button is, and update while user changes base size. This would require a new spot for clear cubes button but it would indicate for the user that changing base size was successful.
