### ISSUE TITLE
Generate random color - icon is undesigned

### ISSUE THREAD

**Issue by mn22nw** [no222bd/1dv411-Webbprojekt-1#138]
Function for random color exists, but we need a good icon in UI.

**Comment by ch222kv** [comment]
Would something like this work:

```javascript
function getRandomColor() {
    var letters = '0123456789ABCDEF'.split('');
    var color = '#';
    for (var i = 0; i < 6; i++ ) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}
```  

Or do we need "nice" colors, that are limited in what color that they select?
How will the random color generation work if we use images instead of colors for the blocks?
Then we could select a random color based on the available colors, which would be much easier.

**Comment by davidsoderberg** [comment]
If we only like to randomize beteween those we have in color selector we could do something like this:
```
function generateColor(){
	var colorsArray = [];
	$('#colorsModal a').each(function( index, link ) {
		colorsArray.push($(link).attr('href'));
	});
	cb.setCubeMaterial(colorsArray[Math.floor((Math.random() * (colorsArray.length-1)))])
}
```

**Comment by ba222ec** [comment]
Issue updated by ba222ec.
